import os

PROJECT_DIR = os.path.dirname(__file__)
ASSETS_DIR = os.path.join(PROJECT_DIR, 'assets')

CONFIG_DIR = ASSETS_DIR
IMAGES_DIR = os.path.join(ASSETS_DIR, 'images')
FONTS_DIR = os.path.join(ASSETS_DIR, 'fonts')
SOUNDS_DIR = os.path.join(ASSETS_DIR, 'sounds')
MAPS_DIR = os.path.join(ASSETS_DIR, 'maps')

SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480

MAP_DISPLAY_WIDTH = 20
MAP_DISPLAY_HEIGHT = 13
MAP_DISPLAY_MID_X = MAP_DISPLAY_WIDTH / 2
MAP_DISPLAY_MID_Y = MAP_DISPLAY_HEIGHT / 2

TILE_WIDTH = 32
TILE_HEIGHT = 32
